/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListSubscriptionResponse } from '../model/models';
import { ApiResponseSubscriptionResponse } from '../model/models';
import { RequestSubscriptionRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface SubscriptionsClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Cancel an awaiting-payment subscription (the saga\&#39;s compensating action)
     * 
     * @endpoint post /api/v1/subscriptions/{id}/cancel
     * @param id 
     */
    cancel(id: string, extraHttpRequestParams?: any): Observable<ApiResponseSubscriptionResponse>;

    /**
     * Confirm payment on an awaiting-payment subscription, materializing the portfolio position
     * 
     * @endpoint post /api/v1/subscriptions/{id}/confirm-payment
     * @param id 
     */
    confirmPayment(id: string, extraHttpRequestParams?: any): Observable<ApiResponseSubscriptionResponse>;

    /**
     * Get a subscription by id (ownership-enforced for an Investor caller)
     * 
     * @endpoint get /api/v1/subscriptions/{id}
     * @param id 
     */
    getById(id: string, extraHttpRequestParams?: any): Observable<ApiResponseSubscriptionResponse>;

    /**
     * List subscriptions for an owner
     * 
     * @endpoint get /api/v1/subscriptions
     * @param ownerId 
     * @param page 
     * @param size 
     */
    listByOwner(ownerId: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListSubscriptionResponse>;

    /**
     * Request a fund subscription — runs the saga\&#39;s synchronous validate/KYC/AML steps
     * 
     * @endpoint post /api/v1/subscriptions
     * @param requestSubscriptionRequest 
     * @param idempotencyKey 
     */
    requestSubscription(requestSubscriptionRequest: RequestSubscriptionRequest, idempotencyKey?: string, extraHttpRequestParams?: any): Observable<ApiResponseSubscriptionResponse>;

}
