/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseFundNavResponse } from '../model/models';
import { ApiResponseListAmlScreeningReportResponse } from '../model/models';
import { ApiResponseListDocumentReportResponse } from '../model/models';
import { ApiResponseListFundNavResponse } from '../model/models';
import { ApiResponseListKycCheckReportResponse } from '../model/models';
import { ApiResponseListPaymentTransferResponse } from '../model/models';
import { ApiResponseListPortfolioResponse } from '../model/models';
import { ApiResponseListSubscriptionReportResponse } from '../model/models';
import { ApiResponsePortfolioDetailResponse } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReportsClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a fund\&#39;s NAV read-model by code
     * 
     * @endpoint get /api/v1/reports/funds/{fundCode}
     * @param fundCode 
     */
    getFund(fundCode: string, extraHttpRequestParams?: any): Observable<ApiResponseFundNavResponse>;

    /**
     * Get a portfolio read-model with its recorded positions
     * 
     * @endpoint get /api/v1/reports/portfolios/{portfolioId}
     * @param portfolioId 
     */
    getPortfolio(portfolioId: string, extraHttpRequestParams?: any): Observable<ApiResponsePortfolioDetailResponse>;

    /**
     * List AML screening read-models, optionally filtered by customer
     * 
     * @endpoint get /api/v1/reports/aml-screenings
     * @param customerId 
     * @param page 
     * @param size 
     */
    listAmlScreenings(customerId?: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListAmlScreeningReportResponse>;

    /**
     * List document read-models, optionally filtered by customer
     * 
     * @endpoint get /api/v1/reports/documents
     * @param customerId 
     * @param page 
     * @param size 
     */
    listDocuments(customerId?: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListDocumentReportResponse>;

    /**
     * List fund NAV read-models
     * 
     * @endpoint get /api/v1/reports/funds
     * @param page 
     * @param size 
     */
    listFunds(page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListFundNavResponse>;

    /**
     * List KYC check read-models, optionally filtered by customer
     * 
     * @endpoint get /api/v1/reports/kyc-checks
     * @param customerId 
     * @param page 
     * @param size 
     */
    listKycChecks(customerId?: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListKycCheckReportResponse>;

    /**
     * List payment transfer read-models, optionally filtered by customer
     * 
     * @endpoint get /api/v1/reports/payments
     * @param customerId 
     * @param page 
     * @param size 
     */
    listPayments(customerId?: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListPaymentTransferResponse>;

    /**
     * List portfolio read-models for an owner
     * 
     * @endpoint get /api/v1/reports/portfolios
     * @param ownerId 
     * @param page 
     * @param size 
     */
    listPortfolios(ownerId: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListPortfolioResponse>;

    /**
     * List subscription read-models, optionally filtered by customer
     * 
     * @endpoint get /api/v1/reports/subscriptions
     * @param customerId 
     * @param page 
     * @param size 
     */
    listSubscriptions(customerId?: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListSubscriptionReportResponse>;

}
