/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface CanaryAdminClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get the current legacy-shadow weight for the customer-lookup canary
     * 
     * @endpoint get /admin/canary/customer-lookup
     */
    getWeight(extraHttpRequestParams?: any): Observable<{ [key: string]: number; }>;

    /**
     * Set the legacy-shadow weight for the customer-lookup canary (0-100, takes effect on the next request, no restart)
     * 
     * @endpoint post /admin/canary/customer-lookup
     * @param legacyWeightPercent 
     */
    setWeight(legacyWeightPercent: number, extraHttpRequestParams?: any): Observable<{ [key: string]: number; }>;

}
