/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';



import { Configuration }                                     from '../configuration';



export interface CustomerLookupCanaryClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Look up a customer by id, weighted-routed to Customer Service or crm-adapter
     * Response carries X-Canary-Target so callers can see which backend actually answered.
     * @endpoint get /api/v1/customer-lookup/{id}
     * @param id 
     */
    lookup(id: string, extraHttpRequestParams?: any): Observable<string>;

}
