/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { TransferResponse } from './transfer-response';


export interface ApiResponseTransferResponse { 
    success?: boolean;
    data?: TransferResponse;
    meta?: PageMeta;
}

