/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RequestTransferRequest { 
    customerId: string;
    ownerId: string;
    amount: number;
    currency: string;
    paymentMethodToken: string;
    reference?: string;
}

