/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransferResponse { 
    id?: string;
    customerId?: string;
    ownerId?: string;
    amount?: number;
    currency?: string;
    paymentMethodToken?: string;
    reference?: string;
    status?: TransferResponse.StatusEnum;
    failureReason?: string;
    createdAt?: string;
    updatedAt?: string;
    settledAt?: string;
}
export namespace TransferResponse {
    export const StatusEnum = {
        Pending: 'PENDING',
        Settled: 'SETTLED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


