/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseKycCheckResponse } from '../model/models';
import { ApiResponseListKycCheckResponse } from '../model/models';
import { KycDecisionRequest } from '../model/models';
import { RequestKycCheckRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface KYCChecksClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Record a compliance decision (approve/reject) on a KYC check, once only
     * 
     * @endpoint post /api/v1/kyc-checks/{id}/decision
     * @param id 
     * @param kycDecisionRequest 
     */
    decide(id: string, kycDecisionRequest: KycDecisionRequest, extraHttpRequestParams?: any): Observable<ApiResponseKycCheckResponse>;

    /**
     * Get a KYC check by id
     * 
     * @endpoint get /api/v1/kyc-checks/{id}
     * @param id 
     */
    getById(id: string, extraHttpRequestParams?: any): Observable<ApiResponseKycCheckResponse>;

    /**
     * List KYC checks for a customer
     * 
     * @endpoint get /api/v1/kyc-checks
     * @param customerId 
     * @param page 
     * @param size 
     */
    listByCustomer(customerId: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListKycCheckResponse>;

    /**
     * Request a new KYC check for a customer
     * 
     * @endpoint post /api/v1/kyc-checks
     * @param requestKycCheckRequest 
     */
    requestCheck(requestKycCheckRequest: RequestKycCheckRequest, extraHttpRequestParams?: any): Observable<ApiResponseKycCheckResponse>;

}
