/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentResponse } from './document-response';
import { PageMeta } from './page-meta';


export interface ApiResponseDocumentResponse { 
    success?: boolean;
    data?: DocumentResponse;
    meta?: PageMeta;
}

