/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentResponse { 
    id?: string;
    customerId?: string;
    documentType?: DocumentResponse.DocumentTypeEnum;
    storageReference?: string;
    status?: DocumentResponse.StatusEnum;
    notes?: string;
    createdAt?: string;
    updatedAt?: string;
}
export namespace DocumentResponse {
    export const DocumentTypeEnum = {
        Passport: 'PASSPORT',
        NationalId: 'NATIONAL_ID',
        DriversLicense: 'DRIVERS_LICENSE',
        ProofOfAddress: 'PROOF_OF_ADDRESS',
        BankStatement: 'BANK_STATEMENT',
        Other: 'OTHER'
    } as const;
    export type DocumentTypeEnum = typeof DocumentTypeEnum[keyof typeof DocumentTypeEnum];
    export const StatusEnum = {
        Uploaded: 'UPLOADED',
        Verified: 'VERIFIED',
        Rejected: 'REJECTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


