/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UploadDocumentRequest { 
    customerId: string;
    documentType: UploadDocumentRequest.DocumentTypeEnum;
    storageReference: string;
}
export namespace UploadDocumentRequest {
    export const DocumentTypeEnum = {
        Passport: 'PASSPORT',
        NationalId: 'NATIONAL_ID',
        DriversLicense: 'DRIVERS_LICENSE',
        ProofOfAddress: 'PROOF_OF_ADDRESS',
        BankStatement: 'BANK_STATEMENT',
        Other: 'OTHER'
    } as const;
    export type DocumentTypeEnum = typeof DocumentTypeEnum[keyof typeof DocumentTypeEnum];
}


