/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { PortfolioValuationResponse } from './portfolio-valuation-response';


export interface ApiResponsePortfolioValuationResponse { 
    success?: boolean;
    data?: PortfolioValuationResponse;
    meta?: PageMeta;
}

