/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { PositionResponse } from './position-response';


export interface ApiResponseListPositionResponse { 
    success?: boolean;
    data?: Array<PositionResponse>;
    meta?: PageMeta;
}

