/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { PortfolioResponse } from './portfolio-response';


export interface ApiResponsePortfolioResponse { 
    success?: boolean;
    data?: PortfolioResponse;
    meta?: PageMeta;
}

