/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PortfolioResponse { 
    id?: string;
    customerId?: string;
    ownerId?: string;
    name?: string;
    currency?: string;
    status?: PortfolioResponse.StatusEnum;
    createdAt?: string;
    updatedAt?: string;
}
export namespace PortfolioResponse {
    export const StatusEnum = {
        Active: 'ACTIVE',
        Closed: 'CLOSED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


