/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PositionValuation } from './position-valuation';


export interface PortfolioValuationResponse { 
    portfolioId?: string;
    currency?: string;
    positions?: Array<PositionValuation>;
    totalValue?: number;
    valuedAt?: string;
}

