/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { ScreeningResponse } from './screening-response';


export interface ApiResponseListScreeningResponse { 
    success?: boolean;
    data?: Array<ScreeningResponse>;
    meta?: PageMeta;
}

