/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ScreeningResponse { 
    id?: string;
    customerId?: string;
    status?: ScreeningResponse.StatusEnum;
    outcome?: ScreeningResponse.OutcomeEnum;
    notes?: string;
    createdAt?: string;
    updatedAt?: string;
    completedAt?: string;
}
export namespace ScreeningResponse {
    export const StatusEnum = {
        InProgress: 'IN_PROGRESS',
        Completed: 'COMPLETED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const OutcomeEnum = {
        Clear: 'CLEAR',
        Hit: 'HIT'
    } as const;
    export type OutcomeEnum = typeof OutcomeEnum[keyof typeof OutcomeEnum];
}


