/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { KycCheckResponse } from './kyc-check-response';


export interface ApiResponseKycCheckResponse { 
    success?: boolean;
    data?: KycCheckResponse;
    meta?: PageMeta;
}

