/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KycCheckResponse { 
    id?: string;
    customerId?: string;
    status?: KycCheckResponse.StatusEnum;
    reason?: string;
    decidedBy?: string;
    createdAt?: string;
    updatedAt?: string;
}
export namespace KycCheckResponse {
    export const StatusEnum = {
        Pending: 'PENDING',
        Approved: 'APPROVED',
        Rejected: 'REJECTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


