/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RequestSubscriptionRequest { 
    customerId: string;
    ownerId: string;
    portfolioId: string;
    fundCode: string;
    quantity: number;
}

