/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionResponse { 
    id?: string;
    customerId?: string;
    ownerId?: string;
    portfolioId?: string;
    fundCode?: string;
    quantity?: number;
    status?: SubscriptionResponse.StatusEnum;
    failureReason?: string;
    createdAt?: string;
    updatedAt?: string;
    confirmedAt?: string;
}
export namespace SubscriptionResponse {
    export const StatusEnum = {
        AwaitingPayment: 'AWAITING_PAYMENT',
        Confirmed: 'CONFIRMED',
        Cancelled: 'CANCELLED',
        Failed: 'FAILED',
        TimedOut: 'TIMED_OUT'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


