/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseDocumentResponse } from '../model/models';
import { ApiResponseListDocumentResponse } from '../model/models';
import { DocumentReviewRequest } from '../model/models';
import { UploadDocumentRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface DocumentsClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a document\&#39;s metadata by id
     * 
     * @endpoint get /api/v1/documents/{id}
     * @param id 
     */
    getById(id: string, extraHttpRequestParams?: any): Observable<ApiResponseDocumentResponse>;

    /**
     * List documents for a customer
     * 
     * @endpoint get /api/v1/documents
     * @param customerId 
     * @param page 
     * @param size 
     */
    listByCustomer(customerId: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListDocumentResponse>;

    /**
     * Reject a document, once only
     * 
     * @endpoint post /api/v1/documents/{id}/reject
     * @param id 
     * @param documentReviewRequest 
     */
    reject(id: string, documentReviewRequest: DocumentReviewRequest, extraHttpRequestParams?: any): Observable<ApiResponseDocumentResponse>;

    /**
     * Register a document\&#39;s metadata (an opaque storage reference, never file bytes)
     * 
     * @endpoint post /api/v1/documents
     * @param uploadDocumentRequest 
     */
    upload(uploadDocumentRequest: UploadDocumentRequest, extraHttpRequestParams?: any): Observable<ApiResponseDocumentResponse>;

    /**
     * Verify a document, once only
     * 
     * @endpoint post /api/v1/documents/{id}/verify
     * @param id 
     * @param documentReviewRequest 
     */
    verify(id: string, documentReviewRequest: DocumentReviewRequest, extraHttpRequestParams?: any): Observable<ApiResponseDocumentResponse>;

}
