/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListTransferResponse } from '../model/models';
import { ApiResponseTransferResponse } from '../model/models';
import { RequestTransferRequest } from '../model/models';
import { TransferFailureRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PaymentsClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Mark a pending transfer failed
     * 
     * @endpoint post /api/v1/payments/{id}/fail
     * @param id 
     * @param transferFailureRequest 
     */
    fail(id: string, transferFailureRequest: TransferFailureRequest, extraHttpRequestParams?: any): Observable<ApiResponseTransferResponse>;

    /**
     * Get a transfer by id (ownership-enforced for an Investor caller)
     * 
     * @endpoint get /api/v1/payments/{id}
     * @param id 
     */
    getById(id: string, extraHttpRequestParams?: any): Observable<ApiResponseTransferResponse>;

    /**
     * List transfers for an owner
     * 
     * @endpoint get /api/v1/payments
     * @param ownerId 
     * @param page 
     * @param size 
     */
    listByOwner(ownerId: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListTransferResponse>;

    /**
     * Request a transfer (async — 202 Accepted, poll GET .../{id} for settlement status)
     * 
     * @endpoint post /api/v1/payments
     * @param requestTransferRequest 
     * @param idempotencyKey 
     */
    requestTransfer(requestTransferRequest: RequestTransferRequest, idempotencyKey?: string, extraHttpRequestParams?: any): Observable<ApiResponseTransferResponse>;

    /**
     * Confirm a pending transfer settled (human/finance-ops confirmation, no real PSP callback)
     * 
     * @endpoint post /api/v1/payments/{id}/settle
     * @param id 
     */
    settle(id: string, extraHttpRequestParams?: any): Observable<ApiResponseTransferResponse>;

}
