global:
  scrape_interval: 5s

scrape_configs:
  - job_name: gateway
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: customer-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: kyc-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8084"]

  - job_name: aml-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8085"]

  - job_name: document-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8086"]

  - job_name: fund-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8087"]

  - job_name: audit-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["host.docker.internal:8083"]
