/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListScreeningResponse } from '../model/models';
import { ApiResponseScreeningResponse } from '../model/models';
import { RequestScreeningRequest } from '../model/models';
import { ScreeningFailureRequest } from '../model/models';
import { ScreeningResultRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AMLScreeningsClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get an AML screening by id
     * 
     * @endpoint get /api/v1/aml/screenings/{id}
     * @param id 
     */
    getById(id: string, extraHttpRequestParams?: any): Observable<ApiResponseScreeningResponse>;

    /**
     * List AML screenings for a customer
     * 
     * @endpoint get /api/v1/aml/screenings
     * @param customerId 
     * @param page 
     * @param size 
     */
    listByCustomer(customerId: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListScreeningResponse>;

    /**
     * Mark a screening technically failed (vendor/system failure, not a compliance outcome)
     * 
     * @endpoint post /api/v1/aml/screenings/{id}/fail
     * @param id 
     * @param screeningFailureRequest 
     */
    recordFailure(id: string, screeningFailureRequest: ScreeningFailureRequest, extraHttpRequestParams?: any): Observable<ApiResponseScreeningResponse>;

    /**
     * Record a compliance result (CLEAR/HIT) on a screening, once only
     * 
     * @endpoint post /api/v1/aml/screenings/{id}/result
     * @param id 
     * @param screeningResultRequest 
     */
    recordResult(id: string, screeningResultRequest: ScreeningResultRequest, extraHttpRequestParams?: any): Observable<ApiResponseScreeningResponse>;

    /**
     * Request an AML screening for a customer (async — 202 Accepted, poll GET .../{id})
     * 
     * @endpoint post /api/v1/aml/screenings
     * @param requestScreeningRequest 
     */
    requestScreening(requestScreeningRequest: RequestScreeningRequest, extraHttpRequestParams?: any): Observable<ApiResponseScreeningResponse>;

}
