/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ApiResponseListPortfolioResponse } from '../model/models';
import { ApiResponseListPositionResponse } from '../model/models';
import { ApiResponsePortfolioResponse } from '../model/models';
import { ApiResponsePortfolioValuationResponse } from '../model/models';
import { ApiResponsePositionResponse } from '../model/models';
import { OpenPortfolioRequest } from '../model/models';
import { RecordPositionRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface PortfoliosClientInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Get a portfolio by id (ownership-enforced for an Investor caller)
     * 
     * @endpoint get /api/v1/portfolios/{id}
     * @param id 
     */
    getById(id: string, extraHttpRequestParams?: any): Observable<ApiResponsePortfolioResponse>;

    /**
     * List portfolios for an owner
     * 
     * @endpoint get /api/v1/portfolios
     * @param ownerId 
     * @param page 
     * @param size 
     */
    listByOwner(ownerId: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListPortfolioResponse>;

    /**
     * List positions held in a portfolio
     * 
     * @endpoint get /api/v1/portfolios/{id}/positions
     * @param id 
     * @param page 
     * @param size 
     */
    listPositions(id: string, page?: number, size?: number, extraHttpRequestParams?: any): Observable<ApiResponseListPositionResponse>;

    /**
     * Open a new portfolio account
     * 
     * @endpoint post /api/v1/portfolios
     * @param openPortfolioRequest 
     */
    openPortfolio(openPortfolioRequest: OpenPortfolioRequest, extraHttpRequestParams?: any): Observable<ApiResponsePortfolioResponse>;

    /**
     * Record a position (fund holding) into a portfolio
     * 
     * @endpoint post /api/v1/portfolios/{id}/positions
     * @param id 
     * @param recordPositionRequest 
     */
    recordPosition(id: string, recordPositionRequest: RecordPositionRequest, extraHttpRequestParams?: any): Observable<ApiResponsePositionResponse>;

    /**
     * Value a portfolio by pricing each held position against Fund Service\&#39;s latest NAV
     * 
     * @endpoint get /api/v1/portfolios/{id}/valuation
     * @param id 
     */
    valuate(id: string, extraHttpRequestParams?: any): Observable<ApiResponsePortfolioValuationResponse>;

}
