/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AmlScreeningReportResponse { 
    screeningId?: string;
    customerId?: string;
    status?: AmlScreeningReportResponse.StatusEnum;
    outcome?: AmlScreeningReportResponse.OutcomeEnum;
    notes?: string;
    failureReason?: string;
    requestedAt?: string;
    completedAt?: string;
    failedAt?: string;
}
export namespace AmlScreeningReportResponse {
    export const StatusEnum = {
        InProgress: 'IN_PROGRESS',
        Completed: 'COMPLETED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const OutcomeEnum = {
        Clear: 'CLEAR',
        Hit: 'HIT'
    } as const;
    export type OutcomeEnum = typeof OutcomeEnum[keyof typeof OutcomeEnum];
}


