/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { FundNavResponse } from './fund-nav-response';
import { PageMeta } from './page-meta';


export interface ApiResponseListFundNavResponse { 
    success?: boolean;
    data?: Array<FundNavResponse>;
    meta?: PageMeta;
}

