/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { SubscriptionReportResponse } from './subscription-report-response';


export interface ApiResponseListSubscriptionReportResponse { 
    success?: boolean;
    data?: Array<SubscriptionReportResponse>;
    meta?: PageMeta;
}

