/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { DocumentReportResponse } from './document-report-response';


export interface ApiResponseListDocumentReportResponse { 
    success?: boolean;
    data?: Array<DocumentReportResponse>;
    meta?: PageMeta;
}

