/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { PaymentTransferResponse } from './payment-transfer-response';


export interface ApiResponseListPaymentTransferResponse { 
    success?: boolean;
    data?: Array<PaymentTransferResponse>;
    meta?: PageMeta;
}

