/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { PortfolioDetailResponse } from './portfolio-detail-response';


export interface ApiResponsePortfolioDetailResponse { 
    success?: boolean;
    data?: PortfolioDetailResponse;
    meta?: PageMeta;
}

