/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PageMeta } from './page-meta';
import { KycCheckReportResponse } from './kyc-check-report-response';


export interface ApiResponseListKycCheckReportResponse { 
    success?: boolean;
    data?: Array<KycCheckReportResponse>;
    meta?: PageMeta;
}

