/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AmlScreeningReportResponse } from './aml-screening-report-response';
import { PageMeta } from './page-meta';


export interface ApiResponseListAmlScreeningReportResponse { 
    success?: boolean;
    data?: Array<AmlScreeningReportResponse>;
    meta?: PageMeta;
}

