/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocumentReportResponse { 
    documentId?: string;
    customerId?: string;
    documentType?: string;
    status?: DocumentReportResponse.StatusEnum;
    notes?: string;
    uploadedAt?: string;
    reviewedAt?: string;
}
export namespace DocumentReportResponse {
    export const StatusEnum = {
        Uploaded: 'UPLOADED',
        Verified: 'VERIFIED',
        Rejected: 'REJECTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


