/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FundNavResponse { 
    fundCode?: string;
    name?: string;
    currency?: string;
    navPerShare?: number;
    asOfDate?: string;
    updatedAt?: string;
}

