/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface KycCheckReportResponse { 
    checkId?: string;
    customerId?: string;
    status?: KycCheckReportResponse.StatusEnum;
    reason?: string;
    decidedBy?: string;
    requestedAt?: string;
    decidedAt?: string;
}
export namespace KycCheckReportResponse {
    export const StatusEnum = {
        Pending: 'PENDING',
        Approved: 'APPROVED',
        Rejected: 'REJECTED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


