/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PaymentTransferResponse { 
    transferId?: string;
    customerId?: string;
    amount?: number;
    currency?: string;
    status?: PaymentTransferResponse.StatusEnum;
    failureReason?: string;
    requestedAt?: string;
    settledAt?: string;
    failedAt?: string;
}
export namespace PaymentTransferResponse {
    export const StatusEnum = {
        Pending: 'PENDING',
        Settled: 'SETTLED',
        Failed: 'FAILED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


