/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PositionResponse } from './position-response';


export interface PortfolioDetailResponse { 
    portfolioId?: string;
    customerId?: string;
    ownerId?: string;
    name?: string;
    currency?: string;
    openedAt?: string;
    positions?: Array<PositionResponse>;
}

