/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PortfolioResponse { 
    portfolioId?: string;
    customerId?: string;
    ownerId?: string;
    name?: string;
    currency?: string;
    openedAt?: string;
}

