/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SubscriptionReportResponse { 
    subscriptionId?: string;
    customerId?: string;
    portfolioId?: string;
    fundCode?: string;
    quantity?: number;
    status?: SubscriptionReportResponse.StatusEnum;
    failureReason?: string;
    reservedAt?: string;
    confirmedAt?: string;
    cancelledAt?: string;
    failedAt?: string;
    timedOutAt?: string;
}
export namespace SubscriptionReportResponse {
    export const StatusEnum = {
        AwaitingPayment: 'AWAITING_PAYMENT',
        Confirmed: 'CONFIRMED',
        Cancelled: 'CANCELLED',
        Failed: 'FAILED',
        TimedOut: 'TIMED_OUT'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
}


